### ISSUE TITLE
No result from subprocess.check_output(...)

### ISSUE THREAD

**Issue by xavier-calland** [rochaporto/collectd-ceph#20]
The commands like "subprocess.check_output(['ceph', 'df', '-f', 'json'])" return a empty string when it's called from collectd.
Other commands in a collectd python plugin are working (like 'ls' or 'pwd').
A simple python script executing the same command ("subprocess.check_output(['ceph', 'df', '-f', 'json'])") works well (out of collectd).
Where is the incompatibility between python/collectd/ceph (user rights, subprocess, ...) ?
Any suggestions ?

OS: ubuntu 1204
Collectd: 5.1.0
Python: 2.7.3

**Comment by Babbleshack** [comment]
I am experiencing the same issue, did you ever find out why this was happening?

**Comment by ksingh7** [comment]
@xavier-calland @rochaporto 

This issue is slightly similar to what i am facing #31 , in my case we are using python2.6.

Do you know some hack , that i can use to make this plugin work against my python2.6 Ceph nodes ?

**Comment by Babbleshack** [comment]
I ended up with
`subprocess.check_output('ceph -s --format json', shell=True)`

The python docs mention some vulnerabilities with `shell=True`, but only in circumstances where the script user would be prompt for the shell commands.

**Comment by benh57** [comment]
Same problem here, hmm. And i have shell=True on, on python 2.7 with Centos 7.2.  Also with ceph-collectd plugin after updating collectd to 5.6.

**Comment by benh57** [comment]
Ah yes, i recall the other fix for this: 

https://github.com/rochaporto/collectd-ceph/issues/28

Just have to 'Import sigchld' in the plugin config. My fix had gotten reverted.
